import {test,expect} from '@playwright/test';

// Only run against a disposable database. These checks change global settings.
test.describe('application configuration',()=>{
 test.skip(!process.env.ICEVIRTUE_CONFIG_TESTS,'Set ICEVIRTUE_CONFIG_TESTS=1 against an isolated test server');
 test('saves settings, preserves stale edits, and protects selected uploads',async({page})=>{
  await page.goto('/login');await page.getByLabel('Username').fill(process.env.ICEVIRTUE_TEST_USER||'demo');await page.getByLabel('Password',{exact:true}).fill(process.env.ICEVIRTUE_TEST_PASSWORD||'recon-demo');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('/');
  await page.goto('/settings/admin');await page.getByRole('link',{name:/Application configurations/}).click();await expect(page.getByText('Saved settings loaded.',{exact:true})).toBeVisible();
  await page.locator('[name=maximum]').fill('30');await page.getByRole('button',{name:'Save password policy'}).click();await expect(page.getByText('Settings saved. Running scans keep their original configuration.',{exact:true})).toBeVisible();await page.reload();await expect(page.getByText('Saved settings loaded.',{exact:true})).toBeVisible();await expect(page.locator('[name=maximum]')).toHaveValue('30');
  await page.locator('#upload-form [name=kind]').selectOption('directory');await page.locator('[name=file]').setInputFiles({name:'browser-list.txt',mimeType:'text/plain',buffer:Buffer.from(`admin-${Date.now()}\nlogin\n`)});await page.getByRole('button',{name:'Upload wordlist',exact:true}).click();await expect(page.getByText('Upload complete. Select the list and save scan configuration to use it.',{exact:true})).toBeVisible();
  const option=page.locator('[name=directory_wordlists] option').filter({hasText:'browser-list.txt'});await expect(option).toBeAttached();const id=await option.getAttribute('value');await page.locator('[name=directory_wordlists]').selectOption(id);await page.locator('[name=skip_directory]').uncheck();await page.getByRole('button',{name:'Save scan configuration'}).click();await expect(page.getByText('Settings saved. Running scans keep their original configuration.',{exact:true})).toBeVisible();
  const row=page.locator('#wordlist-list li').filter({hasText:'browser-list.txt'});await row.getByRole('button',{name:'Delete',exact:true}).click();await expect(page.getByText('wordlist is selected or used by a running scan',{exact:true})).toBeVisible();
  const csrf=await page.locator('#application-settings').getAttribute('data-csrf');const state=(await (await page.request.get('/api/admin/configuration')).json()).configuration;
  const result=await page.request.put('/api/admin/configuration/tools',{headers:{'X-CSRF-Token':csrf},data:{revision:state.revision,settings:{...state.tools,waf_timeout_seconds:31}}});expect(result.status()).toBe(200);
  await page.locator('[name=maximum]').fill('29');await page.getByRole('button',{name:'Save password policy'}).click();await expect(page.getByText(/settings changed; reload before saving/)).toBeVisible();await expect(page.locator('[name=maximum]')).toHaveValue('29');
  await page.reload();await expect(page.getByText('Saved settings loaded.',{exact:true})).toBeVisible();await page.locator('[name=skip_directory]').check();await page.locator('[name=directory_wordlists]').selectOption([]);await page.getByRole('button',{name:'Save scan configuration'}).click();await expect(page.getByText('Settings saved. Running scans keep their original configuration.',{exact:true})).toBeVisible();await row.getByRole('button',{name:'Delete',exact:true}).click();await expect(page.getByText('Wordlist deleted.',{exact:true})).toBeVisible();
  await page.goto('/settings/admin/users/new');const password=page.locator('[name=password]');await password.fill('😀'.repeat(19));expect(await password.evaluate(el=>el.validity.valid)).toBe(false);await expect(password).toHaveValue('😀'.repeat(19));
 });
});
